### ISSUE TITLE
无法下载了

### ISSUE THREAD

**Issue by helloyan** [IvanWoo/taiwan-ebooks-downloader#4]
无法下载了，好像连接变更了，能否更新？

**Comment by helloyan** [comment]
示例下载地址：https://taiwanebook.ncl.edu.tw/ebkFiles/NCL-9900007546/NCL-9900007546F01.PDF#pdfjs.action=download

**Comment by IvanWoo** [comment]
@helloyan 刚刚在 Chrome 里使用 `v 0.5.0` 进行了测试，可以正常的载入文档后下载。欢迎提 PR 用来修复可能持续存在于 Opera 下的 bug。感谢

<img width="1680" alt="Screen Shot 2021-08-16 at 9 07 36 AM" src="https://user-images.githubusercontent.com/15613549/129568545-19f08f6d-72e5-441f-b0c9-0b5214093130.png">

**Comment by helloyan** [comment]
确实是opera下特定bug，修bug不太熟，先用chrome顶着
